version: "3"
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'
services:
  go-server:
    build:
      context: ./dongtai-grpc-go
      dockerfile: ./Dockerfile
    container_name: go-server
    restart: always
    ports:
      - '8888:8888'
    entrypoint: ["./server"]
    volumes:
      - "./dongtai-go-agent-config.yaml:/dongtai/dongtai-go-agent-config.yaml"
      - "./dongtai-grpc-go/index.html:/dongtai/index.html"
    networks:
      network:
        ipv4_address: 177.7.0.11
  go-client:
    build:
      context: ./dongtai-grpc-go
      dockerfile: ./Dockerfile
    container_name: go-client
    restart: always
    entrypoint: ["./client"]
    volumes:
      - "./dongtai-go-agent-config.yaml:/dongtai/dongtai-go-agent-config.yaml"
      - "./dongtai-grpc-go/index.html:/dongtai/index.html"
    depends_on:
      - server
    ports:
      - '8086:8080'
    networks:
      network:
        ipv4_address: 177.7.0.12
